Fix backwards compatibility usage of Get*ProcAddrTable
oneapi-src/level-zero pull request #231
Opened 2024-11-06 19:07 UTC by lisanna-dettwyler

Make the results of certain Get*ProcAddrTable calls in ze_libddi.cpp ignored as not all drivers will implement these functions. These functions populate different sections of DDI tables in the lib component.

Fixes #196
Relates to VLCLJ-2339

2024-11-06 19:08 UTC, lisanna-dettwyler commented
This will support drivers implementing only spec 1.0 functions

2024-11-06 19:29 UTC, nrspruit commented
@lisanna-dettwyler ,

Can you do the same in the zesDdiTableInit and zetDdiTableInit because the error will occur there too.

2024-11-07 01:54 UTC, rwmcguir commented
Just double checking, this isn't something that needs added to the Mako scripts?

2024-11-09 00:12 UTC, nrspruit approved these changes

2024-11-09 00:48 UTC, nrspruit requested changes
Add the logic to generate this code from https://github.com/oneapi-src/level-zero/blob/master/scripts/templates/libddi.cpp.mako

2024-11-09 00:48 UTC, nrspruit commented
> Just double checking, this isn't something that needs added to the Mako scripts?

Yes, I just realized, this will need to be changed here such that the code gen will create this:
https://github.com/oneapi-src/level-zero/blob/master/scripts/templates/libddi.cpp.mako

2024-11-14 21:15 UTC, nrspruit approved these changes

2024-11-14 21:17 UTC, merged